// Generated by CoffeeScript 1.6.2
(function() {
  var CollectionView, Post, PostsView, _ref,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  CollectionView = require('views/base/collection-view');

  Post = require('views/post/post-view');

  module.exports = PostsView = (function(_super) {
    __extends(PostsView, _super);

    function PostsView() {
      _ref = PostsView.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    PostsView.prototype.className = 'topic-posts';

    PostsView.prototype.itemView = Post;

    return PostsView;

  })(CollectionView);

}).call(this);
