// Generated by CoffeeScript 1.6.2
(function() {
  var CollectionView, Topic, TopicsView, _ref,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  CollectionView = require('views/base/collection-view');

  Topic = require('views/topic/topic-view');

  module.exports = TopicsView = (function(_super) {
    __extends(TopicsView, _super);

    function TopicsView() {
      _ref = TopicsView.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    TopicsView.prototype.itemView = Topic;

    return TopicsView;

  })(CollectionView);

}).call(this);
