// Generated by CoffeeScript 1.6.2
(function() {
  var SpinnerView, View, template, _ref,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  View = require('views/base/view');

  template = require('./templates/spinner');

  module.exports = SpinnerView = (function(_super) {
    __extends(SpinnerView, _super);

    function SpinnerView() {
      _ref = SpinnerView.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    SpinnerView.prototype.autoRender = true;

    SpinnerView.prototype.containerMethod = 'html';

    SpinnerView.prototype.template = template;

    SpinnerView.prototype.initialize = function(options) {
      SpinnerView.__super__.initialize.apply(this, arguments);
      return this.previous = options.container.html();
    };

    SpinnerView.prototype.dispose = function() {
      $(this.container).html(this.previous);
      delete this.previous;
      return SpinnerView.__super__.dispose.apply(this, arguments);
    };

    return SpinnerView;

  })(View);

}).call(this);
