// Generated by CoffeeScript 1.6.2
(function() {
  var RepoView, View, template, _ref,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  View = require('views/base/view');

  template = require('./templates/repo');

  module.exports = RepoView = (function(_super) {
    __extends(RepoView, _super);

    function RepoView() {
      _ref = RepoView.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    RepoView.prototype.className = 'user-repo';

    RepoView.prototype.tagName = 'li';

    RepoView.prototype.template = template;

    return RepoView;

  })(View);

}).call(this);
