// Generated by CoffeeScript 1.6.2
(function() {
  var Model, Repo, User, _ref,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Model = require('models/base/model');

  User = require('models/user');

  module.exports = Repo = (function(_super) {
    __extends(Repo, _super);

    function Repo() {
      _ref = Repo.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    Repo.prototype.urlKey = 'name';

    Repo.prototype.urlPath = function() {
      return "/users/" + (this.get('user').get('login')) + "/repos/";
    };

    Repo.prototype.parse = function(response) {
      var user;

      user = new User(_.extend(response.user, {}));
      return _.extend(response, {
        user: user
      });
    };

    return Repo;

  })(Model);

}).call(this);
