// Generated by CoffeeScript 1.6.2
(function() {
  var Model, Repo, Topic, User, _ref,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Model = require('models/base/model');

  User = require('models/user');

  Repo = require('models/repo');

  module.exports = Topic = (function(_super) {
    __extends(Topic, _super);

    function Topic() {
      _ref = Topic.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    Topic.prototype.urlKey = 'number';

    Topic.prototype.urlPath = function() {
      return "/users/" + (this.get('repo').get('user').get('login')) + "/repos/" + (this.get('repo').get('name')) + "/topics/";
    };

    Topic.prototype.parse = function(response) {
      var Post, repo, user;

      Post = require('models/post');
      user = new User(_.extend(response.repo.user, {}));
      repo = new Repo(_.extend(response.repo, {
        user: user
      }));
      return _.extend(response, {
        repo: repo
      });
    };

    return Topic;

  })(Model);

}).call(this);
