// Generated by CoffeeScript 1.6.2
(function() {
  var CollectionView, User, UsersView, _ref,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  CollectionView = require('views/base/collection-view');

  User = require('views/user/user-view');

  module.exports = UsersView = (function(_super) {
    __extends(UsersView, _super);

    function UsersView() {
      _ref = UsersView.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    UsersView.prototype.className = 'users';

    UsersView.prototype.itemView = User;

    return UsersView;

  })(CollectionView);

}).call(this);
