// Generated by CoffeeScript 1.6.2
(function() {
  var UserView, View, template, _ref,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  template = require('./templates/user');

  View = require('views/base/view');

  module.exports = UserView = (function(_super) {
    __extends(UserView, _super);

    function UserView() {
      _ref = UserView.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    UserView.prototype.className = 'user';

    UserView.prototype.tagName = 'span';

    UserView.prototype.template = template;

    return UserView;

  })(View);

}).call(this);
