// Generated by CoffeeScript 1.6.2
(function() {
  var Chaplin, support, utils;

  utils = require('lib/utils');

  Chaplin = require('chaplin');

  support = utils.beget(Chaplin.support);

  module.exports = support;

}).call(this);
